[pytest]
addopts = -p no:xonsh
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =
    error
    error::ResourceWarning
    # TODO remove when cached-property fixes asyncio.iscoroutinefunction usage (https://github.com/pydanny/cached-property/pull/359)
    ignore:.*asyncio\.iscoroutinefunction.*deprecated.*:DeprecationWarning:cached_property$
markers =
    cli: tests for cli interface
