# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Homebrew-deploy

on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tap Repository
        uses: actions/checkout@v2
        with:
          repository: doronz88/homebrew-tap
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update Formula
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          import requests
          import hashlib
          import re
          from urllib.request import urlopen

          # Your software's PyPI package name
          package_name = "pymobiledevice3"
          response = requests.get(f"https://pypi.org/pypi/{package_name}/json").json()
          latest_version = response['info']['version']
          url = next((item for item in response['releases'][latest_version] if item['url'].endswith('.tar.gz')), None)['url']
          
          # Calculate sha256 checksum in chunks
          sha256 = hashlib.sha256()
          with urlopen(url) as f:
              for chunk in iter(lambda: f.read(4096), b""):
                  sha256.update(chunk)
          hexdigest = sha256.hexdigest()

          formula_path = "Formula/pymobiledevice3.rb"
          with open(formula_path, 'r') as file:
            data = file.read()

          # Update version, url, and sha256 in the formula file
          data = re.sub(r'url ".+?"', f'url "{url}"', data)
          data = re.sub(r'version "\d+\.\d+\.\d+"', f'version "{latest_version}"', data)
          data = re.sub(r'sha256 "\w+"', f'sha256 "{hexdigest}"', data)

          with open(formula_path, 'w') as file:
            file.write(data)
        shell: python

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/pymobiledevice3.rb
          git commit -m "Update pymobiledevice3 formula to version ${{ env.LATEST_VERSION }}"
          git push